name: Continuous Integration

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["Auto Merge PR"]
    types:
      - completed

jobs:
  test:
    name: "Integration Testing"
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd "pg_isready -U user -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install dependencies
        run: mvn install -DskipTests
      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U user; do
            sleep 1
          done
      - name: Apply schema
        run: psql postgresql://user:password@localhost:5432/testdb -f src/main/resources/db/schema.sql
      - name: Populate data
        run: psql postgresql://user:password@localhost:5432/testdb -f src/main/resources/db/data.sql
      - name: Build with Maven and Run Integration Tests
        env:
          QUIZBOT_TELEGRAM_TOKEN: ${{secrets.QUIZBOT_TELEGRAM_TOKEN}}
          JDBC_DATABASE_URL: jdbc:postgresql://localhost:5432/testdb?password=password&user=user
        run: mvn verify --batch-mode --fail-at-end

